# Generated by Django 5.0.7 on 2025-02-22 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('message', models.TextField(verbose_name='message')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('is_checked', models.BooleanField(default=False, verbose_name='is checked')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='username')),
                ('email', models.EmailField(max_length=150, verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='last name')),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('fa', 'persian')], default='en', max_length=64, null=True, verbose_name='language')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='phone')),
                ('state', models.CharField(blank=True, choices=[('Alberta', 'Alberta'), ('British Columbia', 'British Columbia'), ('Manitoba', 'Manitoba'), ('New Brunswick', 'New Brunswick'), ('Newfoundland and Labrador', 'Newfoundland And Labrador'), ('Nova Scotia', 'Nova Scotia'), ('Ontario', 'Ontario'), ('Prince Edward Island', 'Prince Edward Island'), ('Quebec', 'Quebec'), ('Saskatchewan', 'Saskatchewan')], default='NoState', max_length=150, null=True, verbose_name='state')),
                ('city', models.CharField(blank=True, choices=[('Vancouver', 'Vancouver'), ('Victoria', 'Victoria'), ('Surrey', 'Surrey'), ('Burnaby', 'Burnaby'), ('Richmond', 'Richmond'), ('Kelowna', 'Kelowna'), ('Kamloops', 'Kamloops'), ('Nanaimo', 'Nanaimo'), ('Prince George', 'Prince George'), ('New Westminster', 'New Westminster'), ('Abbotsford', 'Abbotsford'), ('Coquitlam', 'Coquitlam'), ('Chilliwack', 'Chilliwack'), ('Langley', 'Langley'), ('Maple Ridge', 'Maple Ridge'), ('Port Coquitlam', 'Port Coquitlam'), ('Vernon', 'Vernon'), ('Saanich', 'Saanich'), ('Delta', 'Delta'), ('White Rock', 'White Rock'), ('West Vancouver', 'West Vancouver'), ('Penticton', 'Penticton'), ('Campbell River', 'Campbell River'), ('North Vancouver', 'North Vancouver'), ('Courtenay', 'Courtenay'), ('Port Moody', 'Port Moody'), ('Fort St. John', 'Fort St John'), ('Salmon Arm', 'Salmon Arm'), ('Duncan', 'Duncan'), ('Parksville', 'Parksville'), ('Squamish', 'Squamish'), ('Merritt', 'Merritt'), ('Terrace', 'Terrace'), ('Rossland', 'Rossland')], default='NoCity', max_length=150, null=True, verbose_name='city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
